let projet1 = document.querySelector(".no1");
let projet12 = document.querySelector(".no12");
let projet2 = document.querySelector(".no2");
let projet3 = document.querySelector(".no3");
let projet1d = document.querySelector(".dno1");
let projet12d = document.querySelector(".dno12");
let projet2d = document.querySelector(".dno2");
let projet3d = document.querySelector(".dno3");
let img1 = document.querySelector(".img1");
let img2 = document.querySelector(".img2");
let img3 = document.querySelector(".img3");
let img4 = document.querySelector(".img4");
let img5 = document.querySelector(".img5");
let img6 = document.querySelector(".img6");
let img7 = document.querySelector(".img7");
let img8 = document.querySelector(".img8");
let img9 = document.querySelector(".img9");
let img10 = document.querySelector(".img10");

projet1.addEventListener("click", function(){
    img1.innerHTML = "<img src='coverb1_1.png' />";
    img2.innerHTML = "<img src='spread1b1_1.png' />";
    img3.innerHTML = "<img src='spread2b1_1.png' />";
    img4.innerHTML = "<img src='spread3b1_1.png' />";
    img5.innerHTML = "";
    img6.innerHTML = "";
    img7.innerHTML = "";
    img8.innerHTML = "";
    img9.innerHTML = "";
    img10.innerHTML = "";
    projet1d.innerHTML = "<p>Aisle Preservation is a book created from a series of screen grabs of aisles in grocery stores captured via google maps and subjected to two variables which manipulate their values to create the resulting images.Both variables the humidity at the location of the grocery store, and the time of the store's closure was recorded, and were applied in an effort to subject these screen grabs to artificial time-like distortion.</p>";
    projet12d.innerHTML = "";
    projet2d.innerHTML = "";
    projet3d.innerHTML = "";
})

projet12.addEventListener("click", function(){
    img1.innerHTML = "<img src='coverb1_2.png' />";
    img2.innerHTML = "<img src='cover1b1_2.png' />";
    img3.innerHTML = "";
    img4.innerHTML = "<img src='spread2b1_2.png' />";
    img5.innerHTML = "";
    img6.innerHTML = "";
    img7.innerHTML = "";
    img8.innerHTML = "<img src='spread6b1_2.png' />";
    img9.innerHTML = "";
    img10.innerHTML = "";
    projet12d.innerHTML = "<p>Aisle Preservation is a book created from a series of screen grabs of aisles in grocery stores captured via google maps and subjected to two variables which manipulate their values to create the resulting images.Both variables the humidity at the location of the grocery store, and the time of the store's closure was recorded, and were applied in an effort to subject these screen grabs to artificial time-like distortion.</p>";
    projet1d.innerHTML = "";
    projet2d.innerHTML = "";
    projet3d.innerHTML = "";
})

projet2.addEventListener("click", function(){
    img1.innerHTML = "<img src='spread1b2.png' />";
    img2.innerHTML = "";
    img3.innerHTML = "";
    img4.innerHTML = "";
    img5.innerHTML = "";
    img6.innerHTML = "";
    img7.innerHTML = "";
    img8.innerHTML = "";
    img9.innerHTML = "";
    img10.innerHTML = "";
    projet12d.innerHTML = "";
    projet1d.innerHTML = "";
    projet2d.innerHTML = "<p>A generative web book of compiled texts and fermented foods throughout history critiqueing the commodification of these highly historic living foods, in the form of grrocery store coupons.</p>";
    projet3d.innerHTML = "";
    
})

projet3.addEventListener("click", function(){
    img1.innerHTML = "<img src='coverb3.png' />";
    img2.innerHTML = "<img src='spread1b3.png' />";
    img3.innerHTML = "";
    img4.innerHTML = "";
    img5.innerHTML = "<img src='spread5b3.png' />";
    img6.innerHTML = "<img src='spread6b3.png' />";
    img7.innerHTML = "<img src='spread7b3.png' />";
    img8.innerHTML = "<img src='cover2b3.png' />";
    img9.innerHTML = "<img src='cover1b3.png' />";
    img10.innerHTML = "";
    projet12d.innerHTML = "";
    projet1d.innerHTML = "";
    projet2d.innerHTML = "";
    projet3d.innerHTML = "<p>SUPER PROMO is a book useing a randomly found video of youtuber Sabrina Sabi going through sales at a supermarket. The captions generated by youtube are then placed on top of the accompanying screenshot from the video. The captions which are essentially giberish highlight the absurdity of commodity fetishism with their simple absurdity, highlighting the ridiculousness of this hyper fixation within capitalism to assign a monetary value to everything in sight. </p>";
    
})
